from datetime import datetime

from sqlalchemy import DateTime, Float, ForeignKey, Integer, String, Text
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column
from sqlalchemy.types import JSON


class Base(DeclarativeBase):
    pass


def utcnow():
    return datetime.utcnow()


class Upload(Base):
    __tablename__ = "uploads"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    mode: Mapped[str] = mapped_column(String(30), index=True)
    section_key: Mapped[str | None] = mapped_column(String(80), nullable=True, index=True)
    original_file_name: Mapped[str] = mapped_column(String(255))
    file_path: Mapped[str] = mapped_column(String(500))
    status: Mapped[str] = mapped_column(String(40), default="previewed")
    table_count: Mapped[int] = mapped_column(Integer, default=0)
    created_at: Mapped[datetime] = mapped_column(DateTime, default=utcnow)


class UploadTable(Base):
    __tablename__ = "upload_tables"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    upload_id: Mapped[int] = mapped_column(ForeignKey("uploads.id"), index=True)
    table_index: Mapped[int] = mapped_column(Integer)
    sheet_name: Mapped[str | None] = mapped_column(String(255), nullable=True)
    header_row_number: Mapped[int | None] = mapped_column(Integer, nullable=True)
    detected_section_key: Mapped[str | None] = mapped_column(String(80), nullable=True, index=True)
    section_confidence: Mapped[float] = mapped_column(Float, default=0.0)
    columns_profile: Mapped[list] = mapped_column(JSON, default=list)
    preview_rows: Mapped[list] = mapped_column(JSON, default=list)
    source_rows: Mapped[list] = mapped_column(JSON, default=list)


class ColumnMapping(Base):
    __tablename__ = "column_mappings"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    upload_id: Mapped[int] = mapped_column(ForeignKey("uploads.id"), index=True)
    table_index: Mapped[int] = mapped_column(Integer, index=True)
    section_key: Mapped[str] = mapped_column(String(80), index=True)
    uploaded_column: Mapped[str] = mapped_column(String(255))
    target_field: Mapped[str | None] = mapped_column(String(120), nullable=True)
    confidence: Mapped[float] = mapped_column(Float, default=0.0)
    status: Mapped[str] = mapped_column(String(40), default="custom_field")
    reason: Mapped[str] = mapped_column(Text, default="")


class Record(Base):
    __tablename__ = "records"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    section_key: Mapped[str] = mapped_column(String(80), index=True)
    asset_id: Mapped[str | None] = mapped_column(String(120), nullable=True, index=True)
    record_data: Mapped[dict] = mapped_column(JSON, default=dict)
    custom_fields: Mapped[dict] = mapped_column(JSON, default=dict)
    derived_audit: Mapped[dict] = mapped_column(JSON, default=dict)
    validation_status: Mapped[str] = mapped_column(String(40), default="valid")
    validation_errors: Mapped[list] = mapped_column(JSON, default=list)
    source_upload_id: Mapped[int | None] = mapped_column(Integer, nullable=True)
    source_table_index: Mapped[int | None] = mapped_column(Integer, nullable=True)
    source_sheet_name: Mapped[str | None] = mapped_column(String(255), nullable=True)
    source_row_number: Mapped[int | None] = mapped_column(Integer, nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime, default=utcnow)
    updated_at: Mapped[datetime] = mapped_column(DateTime, default=utcnow, onupdate=utcnow)


class PortfolioFlatRecord(Base):
    __tablename__ = "portfolio_flat_records"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    asset_id: Mapped[str] = mapped_column(String(120), unique=True, nullable=False, index=True)
    property_name: Mapped[str | None] = mapped_column(Text, nullable=True)
    asset_type: Mapped[str | None] = mapped_column(Text, nullable=True)
    ownership_type: Mapped[str | None] = mapped_column(Text, nullable=True)
    address: Mapped[str | None] = mapped_column(Text, nullable=True)
    city: Mapped[str | None] = mapped_column(Text, nullable=True)
    micromarket: Mapped[str | None] = mapped_column(Text, nullable=True)
    latitude: Mapped[float | None] = mapped_column(Float, nullable=True)
    longitude: Mapped[float | None] = mapped_column(Float, nullable=True)
    owner_name: Mapped[str | None] = mapped_column(Text, nullable=True)
    spv_entity: Mapped[str | None] = mapped_column(Text, nullable=True)
    title_status: Mapped[str | None] = mapped_column(Text, nullable=True)
    encumbrance_status: Mapped[str | None] = mapped_column(Text, nullable=True)
    legal_disputes: Mapped[str | None] = mapped_column(Text, nullable=True)
    approvals: Mapped[str | None] = mapped_column(Text, nullable=True)
    lease_ownership_documents: Mapped[str | None] = mapped_column(Text, nullable=True)
    land_area: Mapped[float | None] = mapped_column(Float, nullable=True)
    built_up_area: Mapped[float | None] = mapped_column(Float, nullable=True)
    carpet_area: Mapped[float | None] = mapped_column(Float, nullable=True)
    leasable_area: Mapped[float | None] = mapped_column(Float, nullable=True)
    floors: Mapped[float | None] = mapped_column(Float, nullable=True)
    units: Mapped[float | None] = mapped_column(Float, nullable=True)
    age_of_property: Mapped[float | None] = mapped_column(Float, nullable=True)
    condition_score: Mapped[float | None] = mapped_column(Float, nullable=True)
    energy_consumption: Mapped[float | None] = mapped_column(Float, nullable=True)
    water_consumption: Mapped[float | None] = mapped_column(Float, nullable=True)
    emissions: Mapped[float | None] = mapped_column(Float, nullable=True)
    waste_generated: Mapped[float | None] = mapped_column(Float, nullable=True)
    green_certification: Mapped[str | None] = mapped_column(Text, nullable=True)
    climate_risk: Mapped[str | None] = mapped_column(Text, nullable=True)
    compliance_status: Mapped[str | None] = mapped_column(Text, nullable=True)
    tenant_health_safety_score: Mapped[float | None] = mapped_column(Float, nullable=True)
    esg_risk_score: Mapped[float | None] = mapped_column(Float, nullable=True)
    acquisition_cost: Mapped[float | None] = mapped_column(Float, nullable=True)
    current_market_value: Mapped[float | None] = mapped_column(Float, nullable=True)
    book_value: Mapped[float | None] = mapped_column(Float, nullable=True)
    valuation_date: Mapped[str | None] = mapped_column(String(80), nullable=True)
    valuation_method: Mapped[str | None] = mapped_column(Text, nullable=True)
    appreciation_depreciation: Mapped[float | None] = mapped_column(Float, nullable=True)
    rental_income: Mapped[float | None] = mapped_column(Float, nullable=True)
    occupancy_income: Mapped[float | None] = mapped_column(Float, nullable=True)
    other_income: Mapped[float | None] = mapped_column(Float, nullable=True)
    total_income: Mapped[float | None] = mapped_column(Float, nullable=True)
    escalation_clause: Mapped[float | None] = mapped_column(Float, nullable=True)
    collection_efficiency: Mapped[float | None] = mapped_column(Float, nullable=True)
    maintenance_cost: Mapped[float | None] = mapped_column(Float, nullable=True)
    property_tax: Mapped[float | None] = mapped_column(Float, nullable=True)
    insurance: Mapped[float | None] = mapped_column(Float, nullable=True)
    utilities: Mapped[float | None] = mapped_column(Float, nullable=True)
    repairs: Mapped[float | None] = mapped_column(Float, nullable=True)
    capex: Mapped[float | None] = mapped_column(Float, nullable=True)
    opex: Mapped[float | None] = mapped_column(Float, nullable=True)
    occupancy: Mapped[float | None] = mapped_column(Float, nullable=True)
    vacant_area: Mapped[float | None] = mapped_column(Float, nullable=True)
    tenant_name: Mapped[str | None] = mapped_column(Text, nullable=True)
    lease_start_date: Mapped[str | None] = mapped_column(String(80), nullable=True)
    lease_end_date: Mapped[str | None] = mapped_column(String(80), nullable=True)
    lock_in_period: Mapped[float | None] = mapped_column(Float, nullable=True)
    renewal_status: Mapped[str | None] = mapped_column(Text, nullable=True)
    loan_amount: Mapped[float | None] = mapped_column(Float, nullable=True)
    lender: Mapped[str | None] = mapped_column(Text, nullable=True)
    interest_rate: Mapped[float | None] = mapped_column(Float, nullable=True)
    loan_tenure: Mapped[float | None] = mapped_column(Float, nullable=True)
    emi: Mapped[float | None] = mapped_column(Float, nullable=True)
    outstanding_principal: Mapped[float | None] = mapped_column(Float, nullable=True)
    ltv: Mapped[float | None] = mapped_column(Float, nullable=True)
    dscr: Mapped[float | None] = mapped_column(Float, nullable=True)
    repayment_schedule: Mapped[str | None] = mapped_column(Text, nullable=True)
    legal_risk: Mapped[str | None] = mapped_column(Text, nullable=True)
    market_risk: Mapped[str | None] = mapped_column(Text, nullable=True)
    tenant_risk: Mapped[str | None] = mapped_column(Text, nullable=True)
    valuation_risk: Mapped[str | None] = mapped_column(Text, nullable=True)
    liquidity_risk: Mapped[str | None] = mapped_column(Text, nullable=True)
    regulatory_risk: Mapped[str | None] = mapped_column(Text, nullable=True)
    red_flag_score: Mapped[float | None] = mapped_column(Float, nullable=True)
    noi: Mapped[float | None] = mapped_column(Float, nullable=True)
    ebitda: Mapped[float | None] = mapped_column(Float, nullable=True)
    cap_rate: Mapped[float | None] = mapped_column(Float, nullable=True)
    irr: Mapped[float | None] = mapped_column(Float, nullable=True)
    roi: Mapped[float | None] = mapped_column(Float, nullable=True)
    yield_percentage: Mapped[float | None] = mapped_column(Float, nullable=True)
    payback_period: Mapped[float | None] = mapped_column(Float, nullable=True)
    cash_on_cash_return: Mapped[float | None] = mapped_column(Float, nullable=True)
    cash_flow_period: Mapped[str | None] = mapped_column(Text, nullable=True)
    opening_value: Mapped[float | None] = mapped_column(Float, nullable=True)
    gross_rental_income: Mapped[float | None] = mapped_column(Float, nullable=True)
    cash_flow_other_income: Mapped[float | None] = mapped_column(Float, nullable=True)
    total_gross_income: Mapped[float | None] = mapped_column(Float, nullable=True)
    operating_expenses: Mapped[float | None] = mapped_column(Float, nullable=True)
    cash_flow_noi: Mapped[float | None] = mapped_column(Float, nullable=True)
    annual_debt_service: Mapped[float | None] = mapped_column(Float, nullable=True)
    net_cash_flow_after_debt: Mapped[float | None] = mapped_column(Float, nullable=True)
    capex_reserve: Mapped[float | None] = mapped_column(Float, nullable=True)
    free_cash_flow: Mapped[float | None] = mapped_column(Float, nullable=True)
    cash_flow_dscr: Mapped[float | None] = mapped_column(Float, nullable=True)
    cash_yield: Mapped[float | None] = mapped_column(Float, nullable=True)
    cash_flow_remarks: Mapped[str | None] = mapped_column(Text, nullable=True)
    market_rent: Mapped[float | None] = mapped_column(Float, nullable=True)
    market_rate: Mapped[float | None] = mapped_column(Float, nullable=True)
    comparable_sales: Mapped[str | None] = mapped_column(Text, nullable=True)
    vacancy_rate: Mapped[float | None] = mapped_column(Float, nullable=True)
    absorption: Mapped[float | None] = mapped_column(Float, nullable=True)
    competitor_supply: Mapped[float | None] = mapped_column(Float, nullable=True)
    title_deed: Mapped[str | None] = mapped_column(Text, nullable=True)
    valuation_report: Mapped[str | None] = mapped_column(Text, nullable=True)
    lease_agreement: Mapped[str | None] = mapped_column(Text, nullable=True)
    tax_receipt: Mapped[str | None] = mapped_column(Text, nullable=True)
    insurance_policy: Mapped[str | None] = mapped_column(Text, nullable=True)
    approval_documents: Mapped[str | None] = mapped_column(Text, nullable=True)
    assigned_user: Mapped[str | None] = mapped_column(Text, nullable=True)
    task_status: Mapped[str | None] = mapped_column(Text, nullable=True)
    next_review_date: Mapped[str | None] = mapped_column(String(80), nullable=True)
    approval_status: Mapped[str | None] = mapped_column(Text, nullable=True)
    workflow_remarks: Mapped[str | None] = mapped_column(Text, nullable=True)
    alerts: Mapped[str | None] = mapped_column(Text, nullable=True)
    audit_trail: Mapped[str | None] = mapped_column(Text, nullable=True)
    acquisition_date: Mapped[str | None] = mapped_column(String(80), nullable=True)
    exit_strategy_acquisition_cost: Mapped[float | None] = mapped_column(Float, nullable=True)
    hold_sell_redevelop_decision: Mapped[str | None] = mapped_column(Text, nullable=True)
    target_exit_value: Mapped[float | None] = mapped_column(Float, nullable=True)
    expected_sale_date: Mapped[str | None] = mapped_column(String(80), nullable=True)
    exit_irr: Mapped[float | None] = mapped_column(Float, nullable=True)
    buyer_interest: Mapped[str | None] = mapped_column(Text, nullable=True)
    repairs_status: Mapped[str | None] = mapped_column(Text, nullable=True)
    amc_status: Mapped[str | None] = mapped_column(Text, nullable=True)
    inspection_status: Mapped[str | None] = mapped_column(Text, nullable=True)
    complaints_open: Mapped[float | None] = mapped_column(Float, nullable=True)
    utilities_status: Mapped[str | None] = mapped_column(Text, nullable=True)
    vendor_name: Mapped[str | None] = mapped_column(Text, nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime, default=utcnow)
    updated_at: Mapped[datetime] = mapped_column(DateTime, default=utcnow, onupdate=utcnow)
