PORTFOLIO_FLAT_FIELD_MAPPING: dict[tuple[str, str], str] = {
    ("asset_identity", "propertyName"): "property_name",
    ("asset_identity", "assetType"): "asset_type",
    ("asset_identity", "ownershipType"): "ownership_type",
    ("asset_identity", "address"): "address",
    ("asset_identity", "city"): "city",
    ("asset_identity", "micromarket"): "micromarket",
    ("asset_identity", "latitude"): "latitude",
    ("asset_identity", "longitude"): "longitude",
    ("ownership_legal", "ownerName"): "owner_name",
    ("ownership_legal", "spvEntity"): "spv_entity",
    ("ownership_legal", "titleStatus"): "title_status",
    ("ownership_legal", "encumbranceStatus"): "encumbrance_status",
    ("ownership_legal", "legalDisputes"): "legal_disputes",
    ("ownership_legal", "approvals"): "approvals",
    ("ownership_legal", "leaseOwnershipDocuments"): "lease_ownership_documents",
    ("physical_details", "landArea"): "land_area",
    ("physical_details", "builtUpArea"): "built_up_area",
    ("physical_details", "carpetArea"): "carpet_area",
    ("physical_details", "leasableArea"): "leasable_area",
    ("physical_details", "floors"): "floors",
    ("physical_details", "units"): "units",
    ("physical_details", "ageOfProperty"): "age_of_property",
    ("physical_details", "conditionScore"): "condition_score",
    ("esg_data", "energyConsumption"): "energy_consumption",
    ("esg_data", "waterConsumption"): "water_consumption",
    ("esg_data", "emissions"): "emissions",
    ("esg_data", "wasteGenerated"): "waste_generated",
    ("esg_data", "greenCertification"): "green_certification",
    ("esg_data", "climateRisk"): "climate_risk",
    ("esg_data", "complianceStatus"): "compliance_status",
    ("esg_data", "tenantHealthSafetyScore"): "tenant_health_safety_score",
    ("esg_data", "esgRiskScore"): "esg_risk_score",
    ("financial_value", "acquisitionCost"): "acquisition_cost",
    ("financial_value", "currentMarketValue"): "current_market_value",
    ("financial_value", "bookValue"): "book_value",
    ("financial_value", "valuationDate"): "valuation_date",
    ("financial_value", "valuationMethod"): "valuation_method",
    ("financial_value", "appreciationDepreciation"): "appreciation_depreciation",
    ("revenue_income", "rentalIncome"): "rental_income",
    ("revenue_income", "occupancyIncome"): "occupancy_income",
    ("revenue_income", "otherIncome"): "other_income",
    ("revenue_income", "totalIncome"): "total_income",
    ("revenue_income", "escalationClause"): "escalation_clause",
    ("revenue_income", "collectionEfficiency"): "collection_efficiency",
    ("expenses", "maintenanceCost"): "maintenance_cost",
    ("expenses", "propertyTax"): "property_tax",
    ("expenses", "insurance"): "insurance",
    ("expenses", "utilities"): "utilities",
    ("expenses", "repairs"): "repairs",
    ("expenses", "capex"): "capex",
    ("expenses", "opex"): "opex",
    ("occupancy_leasing", "occupancy"): "occupancy",
    ("occupancy_leasing", "vacantArea"): "vacant_area",
    ("occupancy_leasing", "tenantName"): "tenant_name",
    ("occupancy_leasing", "leaseStartDate"): "lease_start_date",
    ("occupancy_leasing", "leaseEndDate"): "lease_end_date",
    ("occupancy_leasing", "lockInPeriod"): "lock_in_period",
    ("occupancy_leasing", "renewalStatus"): "renewal_status",
    ("loan_debt", "loanAmount"): "loan_amount",
    ("loan_debt", "lender"): "lender",
    ("loan_debt", "interestRate"): "interest_rate",
    ("loan_debt", "loanTenure"): "loan_tenure",
    ("loan_debt", "emi"): "emi",
    ("loan_debt", "outstandingPrincipal"): "outstanding_principal",
    ("loan_debt", "ltv"): "ltv",
    ("loan_debt", "dscr"): "dscr",
    ("loan_debt", "repaymentSchedule"): "repayment_schedule",
    ("risk_fields", "legalRisk"): "legal_risk",
    ("risk_fields", "marketRisk"): "market_risk",
    ("risk_fields", "tenantRisk"): "tenant_risk",
    ("risk_fields", "valuationRisk"): "valuation_risk",
    ("risk_fields", "liquidityRisk"): "liquidity_risk",
    ("risk_fields", "regulatoryRisk"): "regulatory_risk",
    ("risk_fields", "redFlagScore"): "red_flag_score",
    ("performance_metrics", "noi"): "noi",
    ("performance_metrics", "ebitda"): "ebitda",
    ("performance_metrics", "capRate"): "cap_rate",
    ("performance_metrics", "irr"): "irr",
    ("performance_metrics", "roi"): "roi",
    ("performance_metrics", "yieldPercentage"): "yield_percentage",
    ("performance_metrics", "paybackPeriod"): "payback_period",
    ("performance_metrics", "cashOnCashReturn"): "cash_on_cash_return",
    ("cash_flow_analysis", "cashFlowPeriod"): "cash_flow_period",
    ("cash_flow_analysis", "openingValue"): "opening_value",
    ("cash_flow_analysis", "grossRentalIncome"): "gross_rental_income",
    ("cash_flow_analysis", "otherIncome"): "cash_flow_other_income",
    ("cash_flow_analysis", "totalGrossIncome"): "total_gross_income",
    ("cash_flow_analysis", "operatingExpenses"): "operating_expenses",
    ("cash_flow_analysis", "noi"): "cash_flow_noi",
    ("cash_flow_analysis", "annualDebtService"): "annual_debt_service",
    ("cash_flow_analysis", "netCashFlowAfterDebt"): "net_cash_flow_after_debt",
    ("cash_flow_analysis", "capexReserve"): "capex_reserve",
    ("cash_flow_analysis", "freeCashFlow"): "free_cash_flow",
    ("cash_flow_analysis", "dscr"): "cash_flow_dscr",
    ("cash_flow_analysis", "cashYield"): "cash_yield",
    ("cash_flow_analysis", "remarks"): "cash_flow_remarks",
    ("market_benchmarking", "marketRent"): "market_rent",
    ("market_benchmarking", "marketRate"): "market_rate",
    ("market_benchmarking", "comparableSales"): "comparable_sales",
    ("market_benchmarking", "vacancyRate"): "vacancy_rate",
    ("market_benchmarking", "absorption"): "absorption",
    ("market_benchmarking", "competitorSupply"): "competitor_supply",
    ("documents", "titleDeed"): "title_deed",
    ("documents", "valuationReport"): "valuation_report",
    ("documents", "leaseAgreement"): "lease_agreement",
    ("documents", "taxReceipt"): "tax_receipt",
    ("documents", "insurancePolicy"): "insurance_policy",
    ("documents", "approvalDocuments"): "approval_documents",
    ("workflow_actions", "assignedUser"): "assigned_user",
    ("workflow_actions", "taskStatus"): "task_status",
    ("workflow_actions", "nextReviewDate"): "next_review_date",
    ("workflow_actions", "approvalStatus"): "approval_status",
    ("workflow_actions", "remarks"): "workflow_remarks",
    ("workflow_actions", "alerts"): "alerts",
    ("workflow_actions", "auditTrail"): "audit_trail",
    ("exit_strategy", "acquisitionDate"): "acquisition_date",
    ("exit_strategy", "acquisitionCost"): "exit_strategy_acquisition_cost",
    ("exit_strategy", "holdSellRedevelopDecision"): "hold_sell_redevelop_decision",
    ("exit_strategy", "targetExitValue"): "target_exit_value",
    ("exit_strategy", "expectedSaleDate"): "expected_sale_date",
    ("exit_strategy", "exitIrr"): "exit_irr",
    ("exit_strategy", "buyerInterest"): "buyer_interest",
    ("operations_maintenance", "repairsStatus"): "repairs_status",
    ("operations_maintenance", "amcStatus"): "amc_status",
    ("operations_maintenance", "inspectionStatus"): "inspection_status",
    ("operations_maintenance", "complaintsOpen"): "complaints_open",
    ("operations_maintenance", "utilitiesStatus"): "utilities_status",
    ("operations_maintenance", "vendorName"): "vendor_name",
}


PORTFOLIO_FLAT_NUMERIC_COLUMNS = {
    "latitude",
    "longitude",
    "land_area",
    "built_up_area",
    "carpet_area",
    "leasable_area",
    "floors",
    "units",
    "age_of_property",
    "condition_score",
    "energy_consumption",
    "water_consumption",
    "emissions",
    "waste_generated",
    "tenant_health_safety_score",
    "esg_risk_score",
    "acquisition_cost",
    "current_market_value",
    "book_value",
    "appreciation_depreciation",
    "rental_income",
    "occupancy_income",
    "other_income",
    "total_income",
    "escalation_clause",
    "collection_efficiency",
    "maintenance_cost",
    "property_tax",
    "insurance",
    "utilities",
    "repairs",
    "capex",
    "opex",
    "occupancy",
    "vacant_area",
    "lock_in_period",
    "loan_amount",
    "interest_rate",
    "loan_tenure",
    "emi",
    "outstanding_principal",
    "ltv",
    "dscr",
    "red_flag_score",
    "noi",
    "ebitda",
    "cap_rate",
    "irr",
    "roi",
    "yield_percentage",
    "payback_period",
    "cash_on_cash_return",
    "opening_value",
    "gross_rental_income",
    "cash_flow_other_income",
    "total_gross_income",
    "operating_expenses",
    "cash_flow_noi",
    "annual_debt_service",
    "net_cash_flow_after_debt",
    "capex_reserve",
    "free_cash_flow",
    "cash_flow_dscr",
    "cash_yield",
    "market_rent",
    "market_rate",
    "vacancy_rate",
    "absorption",
    "competitor_supply",
    "exit_strategy_acquisition_cost",
    "target_exit_value",
    "exit_irr",
    "complaints_open",
}


PORTFOLIO_FLAT_COLUMNS = sorted(set(PORTFOLIO_FLAT_FIELD_MAPPING.values()))
