DEFAULT_DISTINCT_DATABASE_VALUES = {
    "transaction_category": [
        "Gifts",
        "Lease",
        "Mortgages",
        "Other",
        "Sale",
    ],
    "unit_configuration": [
        "<1Bhk",
        "<1BHK",
        ">3Bhk",
        ">3BHK",
        "1 B/R",
        "1.5BHK",
        "10 B/R",
        "1Bhk",
        "1BHK",
        "2 B/R",
        "2.25BHK",
        "2.5Bhk",
        "2.5BHK",
        "2.75BHK",
        "2Bhk",
        "2BHK",
        "3 B/R",
        "3.5Bhk",
        "3Bhk",
        "3BHK",
        "4 B/R",
        "4Bhk",
        "5 B/R",
        "5Bhk",
        "6 B/R",
        "7 B/R",
        "8 B/R",
        "9 B/R",
        "FLAT",
        "Gym",
        "Office",
        "OFFICE",
        "Others",
        "OTHERS",
        "Penthouse",
        "Shop",
        "SHOP",
        "Single Room",
        "Store",
        "Studio",
    ],
    "property_type": [
        "Flat",
        "Office",
        "Others",
        "Shop",
        "Villa",
        "Plot"
    ],
    "project_type": [
        "Agricultural",
        "Commercial",
        "Hospitality",
        "Industrial",
        "Industrial / Commercial",
        "Industrial / Commercial / Residential",
        "Mixed Development (Residential & Commercial)",
        "Multi-Use",
        "Other",
        "Plotted Development",
        "Residential",
        "Residential / Commercial",
        "Residential+Commercial",
        "Storage",
    ],
}


DEFAULT_ATTRIBUTE_MASTER_TABLES = {
    column_name: {
        "column_name": column_name,
        "allowed_values": values,
    }
    for column_name, values in DEFAULT_DISTINCT_DATABASE_VALUES.items()
}
