FIELD_EXAMPLES = {
    "assetId": ["AST-001", "PROP-1001", "BLDG-45"],
    "propertyName": ["Omicron Commerz", "Balewadi IT Hub", "Westfield Business Park"],
    "assetType": ["Grade A Office", "Retail Mall", "Industrial Warehouse"],
    "ownershipType": ["Freehold", "Leasehold", "Joint Venture"],
    "address": ["Plot 12, Baner Road, Pune", "Survey No. 45, Kharadi, Pune", "Tower B, Business Park, Hinjewadi"],
    "city": ["Pune", "Mumbai", "Bengaluru"],
    "micromarket": ["Baner", "Balewadi", "Hinjewadi"],
    "latitude": ["18.559", "19.076", "12.9716"],
    "longitude": ["73.7868", "72.8777", "77.5946"],
    "ownerName": ["ABC Realty Holdings Pvt Ltd", "Pune Commercial Assets LLP", "Westfield Propco Pvt Ltd"],
    "spvEntity": ["Balewadi Asset SPV Pvt Ltd", "Office Park PropCo LLP", "REIT Holdco Entity 1"],
    "titleStatus": ["Clear title", "Title due diligence pending", "Mutation pending"],
    "encumbranceStatus": ["No encumbrance", "Mortgage with HDFC Bank", "Charge registered"],
    "legalDisputes": ["No pending dispute", "Tenant litigation pending", "Property tax appeal open"],
    "approvals": ["OC received", "Fire NOC pending", "Building plan approved"],
    "leaseOwnershipDocuments": ["lease_agreement.pdf", "title_deed.pdf", "document link"],
    "landArea": ["2.5 acres", "120000 sq ft plot", "45000 sq m land"],
    "builtUpArea": ["850000 sq ft", "1.2 million sq ft", "150000 sq ft built-up"],
    "carpetArea": ["650000 sq ft", "82000 sq ft carpet", "10000 sq m carpet area"],
    "leasableArea": ["720000 sq ft", "95000 sq ft leasable", "1.1 million sq ft GLA"],
    "floors": ["G+12", "Basement + Ground + 8", "22 floors"],
    "units": ["24 office units", "120 apartments", "8 retail units"],
    "ageOfProperty": ["4 years", "12 years", "Under construction"],
    "conditionScore": ["8/10", "Grade A condition", "Needs refurbishment"],
    "energyConsumption": ["12000", "45000 kWh", "9800"],
    "waterConsumption": ["3000", "12000 KL", "800"],
    "emissions": ["120", "450 tCO2e", "80"],
    "wasteGenerated": ["12", "45 tons", "8"],
    "greenCertification": ["LEED Gold", "IGBC Platinum", "GRIHA 4 Star"],
    "climateRisk": ["Low flood risk", "Heat stress exposure", "Moderate climate risk"],
    "complianceStatus": ["ESG compliant", "Audit pending", "Non-compliant on water reporting"],
    "tenantHealthSafetyScore": ["8", "92", "Good"],
    "esgRiskScore": ["3", "Low", "7.5"],
    "acquisitionCost": ["1250000", "INR 12,50,000", "1.2 Cr"],
    "currentMarketValue": ["1420000", "INR 14,20,000", "2.5 Cr"],
    "bookValue": ["1080000", "INR 10,80,000", "950000"],
    "valuationDate": ["2025-03-31", "31/03/2025", "Mar 31 2025"],
    "valuationMethod": ["Market Approach", "DCF Income Approach", "Depreciated Replacement Cost"],
    "appreciationDepreciation": ["170000", "-85000", "12%"],
    "rentalIncome": ["240000", "INR 2,40,000", "20000/month"],
    "occupancyIncome": ["228000", "INR 2,28,000", "95% rent collected"],
    "otherIncome": ["35000", "parking income", "common area recovery"],
    "totalIncome": ["275000", "INR 2,75,000", "total gross rental income"],
    "escalationClause": ["5% yearly", "3% every year", "10% after 3 years"],
    "collectionEfficiency": ["95", "95%", "0.95"],
    "maintenanceCost": ["60000", "INR 60,000", "5000/month"],
    "propertyTax": ["28000", "INR 28,000", "annual tax"],
    "insurance": ["12000", "INR 12,000", "policy premium"],
    "utilities": ["36000", "electricity and water charges", "INR 36,000 utilities"],
    "repairs": ["18000", "HVAC repair cost", "INR 18,000 plumbing repairs"],
    "capex": ["150000", "lift modernization capex", "INR 1,50,000 facade upgrade"],
    "opex": ["154000", "annual operating expense", "INR 1,54,000 property opex"],
    "occupancy": ["95", "95%", "0.95"],
    "vacantArea": ["5000", "2500 sq ft", "0"],
    "tenantName": ["Infosys Ltd", "HDFC Bank Ltd", "Reliance Retail Ltd"],
    "leaseStartDate": ["2024-04-01", "01/04/2024", "Apr 1 2024"],
    "leaseEndDate": ["2031-03-31", "31/03/2031", "Mar 31 2031"],
    "lockInPeriod": ["36", "36 months", "3 years"],
    "renewalStatus": ["Renewed for 3 years", "Renewal negotiation pending", "Lease expired"],
    "loanAmount": ["7000000", "INR 70,00,000", "7 Cr"],
    "lender": ["HDFC Bank", "ICICI Bank", "Axis Bank"],
    "interestRate": ["8.75", "8.75%", "0.0875"],
    "loanTenure": ["120", "180 months", "15 years"],
    "emi": ["72500", "INR 72,500", "monthly EMI"],
    "outstandingPrincipal": ["5800000", "principal OS", "INR 58,00,000"],
    "ltv": ["65", "65%", "0.65"],
    "dscr": ["1.4", "1.25", "2.0"],
    "repaymentSchedule": ["Monthly amortization", "Quarterly repayment", "repayment_schedule.pdf"],
    "legalRisk": ["Low legal risk", "Title dispute pending", "Tenant litigation risk"],
    "marketRisk": ["Low vacancy market", "Oversupply risk", "Rent softening risk"],
    "tenantRisk": ["Low tenant risk", "Single tenant concentration", "High tenant churn"],
    "valuationRisk": ["Low valuation risk", "Overvalued vs comps", "Valuation review required"],
    "liquidityRisk": ["Liquid Grade A office", "Moderate liquidity", "Illiquid non-core asset"],
    "regulatoryRisk": ["Low regulatory risk", "Fire NOC pending", "Zoning approval risk"],
    "redFlagScore": ["2", "8", "Low"],
    "noi": ["120000", "net operating income", "INR 1,20,000"],
    "ebitda": ["110000", "INR 1,10,000", "EBITDA"],
    "capRate": ["8", "8%", "0.08"],
    "irr": ["14", "14%", "0.14"],
    "roi": ["12", "12%", "0.12"],
    "yieldPercentage": ["7", "7%", "0.07"],
    "paybackPeriod": ["6", "6 years", "72 months"],
    "cashOnCashReturn": ["9", "9%", "0.09"],
    "cashFlowPeriod": ["FY2025", "Q1 2025", "2025-03"],
    "openingValue": ["1000000", "INR 10,00,000", "opening NAV"],
    "grossRentalIncome": ["240000", "gross rent", "INR 2,40,000"],
    "totalGrossIncome": ["275000", "gross income", "INR 2,75,000"],
    "operatingExpenses": ["154000", "opex", "INR 1,54,000"],
    "annualDebtService": ["870000", "annual EMI", "debt service"],
    "freeCashFlow": ["50000", "FCF", "INR 50,000"],
    "cashYield": ["6", "6%", "0.06"],
    "marketRent": ["80/sqft", "INR 80", "market rent"],
    "marketRate": ["12000/sqft", "INR 12,000", "market rate"],
    "comparableSales": ["Nearby office sale at INR 12,000/sqft", "Comparable mall transaction", "Recent warehouse sale benchmark"],
    "vacancyRate": ["8", "8%", "0.08"],
    "absorption": ["120000", "sq ft absorbed", "300 units"],
    "competitorSupply": ["500000", "nearby supply", "250 units"],
    "titleDeed": ["title_deed.pdf", "document URL", "deed file"],
    "valuationReport": ["valuation_report.pdf", "report URL", "valuation file"],
    "leaseAgreement": ["lease.pdf", "agreement URL", "lease document"],
    "taxReceipt": ["tax_receipt.pdf", "receipt URL", "tax file"],
    "insurancePolicy": ["policy.pdf", "policy URL", "insurance document"],
    "approvalDocuments": ["approval.pdf", "NOC.pdf", "approval URL"],
    "assignedUser": ["asset.manager@example.com", "leasing_head", "portfolio_admin"],
    "taskStatus": ["Inspection pending", "Valuation downloaded", "Lease review completed"],
    "nextReviewDate": ["2026-05-13", "13/05/2026", "May 13 2026"],
    "approvalStatus": ["Approved", "Pending", "Rejected"],
    "remarks": ["Lease renewal needs review", "Valuation report downloaded", "Follow up with facility team"],
    "alerts": ["Valuation review due", "High vacancy risk", "Missing title document"],
    "auditTrail": ["created by portfolio_admin", "valuation downloaded at timestamp", "updated by asset manager"],
    "acquisitionDate": ["2020-04-01", "01/04/2020", "Apr 1 2020"],
    "holdSellRedevelopDecision": ["Hold for rental yield", "Sell non-core asset", "Redevelop retail block"],
    "targetExitValue": ["2500000", "INR 25,00,000", "expected sale value"],
    "expectedSaleDate": ["2028-03-31", "31/03/2028", "Mar 31 2028"],
    "exitIrr": ["16", "16%", "0.16"],
    "buyerInterest": ["High buyer interest", "Low investor interest", "3 institutional buyers interested"],
    "repairsStatus": ["HVAC repair open", "Lift repair completed", "Facade work in progress"],
    "amcStatus": ["AMC active", "AMC expired", "AMC renewal pending"],
    "inspectionStatus": ["Fire inspection passed", "Structural inspection pending", "Safety audit failed"],
    "complaintsOpen": ["0", "4", "12"],
    "utilitiesStatus": ["Electricity and water active", "Power connection disconnected", "DG backup pending"],
    "vendorName": ["CBRE Facility Services", "JLL Property Management", "XYZ Maintenance Contractors"],
}


FIELD_DOMAIN_ALIASES = {
    "assetId": ["asset number", "asset code", "property id", "property code", "building id", "site id"],
    "propertyName": ["property", "project", "building", "asset name", "project name", "building name"],
    "assetType": ["property type", "building type", "asset class", "real estate type", "use type"],
    "ownershipType": ["holding type", "title type", "ownership category"],
    "address": ["site address", "property address", "location address"],
    "city": ["district", "city name", "municipality"],
    "micromarket": ["submarket", "micro market", "locality", "location", "neighbourhood"],
    "ownerName": ["owner", "landlord", "lessor", "holding company"],
    "spvEntity": ["spv", "propco", "holding entity", "asset entity"],
    "titleStatus": ["title", "title clearance", "land title"],
    "encumbranceStatus": ["encumbrance", "charge status", "mortgage status", "lien status"],
    "legalDisputes": ["dispute", "litigation", "court case", "legal case", "pending case"],
    "approvals": ["approval", "noc", "oc", "cc", "building approval"],
    "leaseOwnershipDocuments": ["ownership docs", "lease docs", "title documents", "property documents", "deed documents"],
    "landArea": ["plot area", "site area", "land size"],
    "builtUpArea": ["bua", "built up area", "constructed area"],
    "carpetArea": ["net usable area", "usable area", "carpet"],
    "leasableArea": ["gla", "gross leasable area", "rentable area", "chargeable area"],
    "floors": ["floor count", "storeys", "levels"],
    "units": ["unit count", "number of units", "apartments", "shops"],
    "ageOfProperty": ["property age", "building age", "asset age", "years old", "construction age"],
    "conditionScore": ["condition", "building condition", "asset condition", "property condition", "condition rating"],
    "energyConsumption": ["energy", "electricity consumption", "power consumption", "kwh", "energy usage"],
    "waterConsumption": ["water", "water usage", "water consumed", "kl consumed", "water consumption"],
    "emissions": ["carbon emissions", "co2", "tco2e", "emission", "ghg emissions"],
    "wasteGenerated": ["waste", "waste generated", "solid waste", "waste tonnage"],
    "greenCertification": ["green certificate", "leed", "igbc", "griha", "sustainability certification"],
    "climateRisk": ["climate", "flood risk", "heat risk", "climate exposure", "environmental risk"],
    "complianceStatus": ["compliance", "esg compliance", "statutory compliance", "audit status"],
    "tenantHealthSafetyScore": ["health safety", "hse score", "tenant safety", "safety score"],
    "esgRiskScore": ["esg score", "esg risk", "sustainability risk", "environment score"],
    "currentMarketValue": ["market value", "current value", "fair value", "asset value", "valuation amount"],
    "acquisitionCost": ["purchase cost", "buying cost", "acquisition value", "purchase price"],
    "bookValue": ["carrying value", "net book value", "nbv"],
    "valuationDate": ["valuation as of", "valuation timestamp", "valuation date"],
    "valuationMethod": ["valuation approach", "method", "valuation basis"],
    "appreciationDepreciation": ["appreciation", "depreciation", "gain loss", "value movement", "change in value"],
    "rentalIncome": ["rent", "lease rent", "annual rent", "rental revenue"],
    "occupancyIncome": ["occupied rent", "effective rent", "occupancy rent"],
    "otherIncome": ["ancillary income", "parking income", "cam recovery", "service income"],
    "totalIncome": ["total revenue", "gross income", "total rent", "total collections", "gross revenue"],
    "escalationClause": ["rent escalation", "escalation", "increment clause"],
    "collectionEfficiency": ["collection rate", "collection %", "recovery efficiency"],
    "maintenanceCost": ["maintenance", "facility maintenance", "fm cost"],
    "propertyTax": ["tax", "municipal tax", "property tax amount"],
    "insurance": ["insurance premium", "property insurance"],
    "utilities": ["electricity", "water", "utility charges", "power and water"],
    "repairs": ["repair cost", "r&m", "repair and maintenance"],
    "capex": ["capital expenditure", "capital expense", "improvement capex"],
    "opex": ["operating expense", "operating cost", "opex amount"],
    "occupancy": ["occupancy percentage", "occupancy rate", "leased percentage"],
    "vacantArea": ["vacancy area", "vacant space", "unleased area", "vacant sq ft"],
    "tenantName": ["tenant", "lessee", "occupier", "tenant company"],
    "leaseStartDate": ["lease start", "commencement date", "rent start date"],
    "leaseEndDate": ["lease end", "expiry date", "lease expiry", "maturity date"],
    "lockInPeriod": ["lock in", "lock-in", "minimum term"],
    "renewalStatus": ["renewal", "extension status", "lease renewal"],
    "loanAmount": ["sanction", "sanction amount", "debt amount", "facility amount", "principal sanctioned"],
    "lender": ["bank", "financier", "financial institution", "lending institution", "nbfc", "loan provider"],
    "interestRate": ["rate", "rate %", "roi", "coupon", "loan rate"],
    "loanTenure": ["tenure", "loan term", "duration", "term months", "maturity period"],
    "emi": ["monthly installment", "instalment", "loan emi", "debt payment"],
    "outstandingPrincipal": ["principal os", "principal outstanding", "outstanding", "loan outstanding"],
    "ltv": ["loan to value", "ltv ratio", "leverage ratio"],
    "dscr": ["debt service coverage", "debt service coverage ratio", "coverage ratio"],
    "repaymentSchedule": ["repayment", "amortization schedule", "payment schedule"],
    "legalRisk": ["legal risk", "litigation risk", "title risk", "dispute risk"],
    "marketRisk": ["market risk", "rent risk", "market volatility", "oversupply risk"],
    "tenantRisk": ["tenant risk", "lessee risk", "occupier risk", "tenant concentration"],
    "valuationRisk": ["valuation risk", "overvaluation", "valuation concern", "pricing risk"],
    "liquidityRisk": ["liquidity risk", "exit liquidity", "saleability", "marketability"],
    "regulatoryRisk": ["regulatory risk", "approval risk", "compliance risk", "zoning risk"],
    "redFlagScore": ["red flag", "red flag score", "risk score", "warning score"],
    "noi": ["net operating income", "noi", "operating income"],
    "ebitda": ["ebitda", "earnings before interest tax depreciation amortization"],
    "capRate": ["cap rate", "capitalization rate", "yield on value"],
    "irr": ["irr", "internal rate of return", "project irr"],
    "roi": ["roi", "return on investment", "investment return"],
    "yieldPercentage": ["yield", "rental yield", "asset yield", "yield percentage"],
    "paybackPeriod": ["payback", "payback period", "recovery period"],
    "cashOnCashReturn": ["cash on cash", "cash return", "coc return"],
    "cashFlowPeriod": ["period", "cash flow period", "financial period", "month", "quarter", "year"],
    "openingValue": ["opening value", "opening balance", "opening nav", "opening asset value"],
    "grossRentalIncome": ["gross rent", "gross rental income", "gross lease income"],
    "totalGrossIncome": ["total gross income", "gross income", "gross revenue"],
    "operatingExpenses": ["operating expense", "operating expenses", "opex", "property operating cost"],
    "annualDebtService": ["annual debt service", "debt service", "annual emi", "loan servicing"],
    "freeCashFlow": ["free cash flow", "fcf", "net cash flow", "cash surplus"],
    "cashYield": ["cash yield", "cash return yield", "yield on cash"],
    "marketRent": ["market rent", "market lease rent", "prevailing rent", "rent benchmark"],
    "marketRate": ["market rate", "market price", "rate per sqft", "market value per sqft"],
    "comparableSales": ["comps", "comparable sales", "benchmark sale", "market comparable"],
    "vacancyRate": ["vacancy", "vacancy rate", "vacant percentage"],
    "absorption": ["absorption", "net absorption", "leasing absorption", "market absorption"],
    "competitorSupply": ["competitive supply", "competitor supply", "new supply", "nearby supply"],
    "titleDeed": ["title deed", "sale deed", "conveyance deed", "deed file"],
    "valuationReport": ["valuation report", "valuation file", "appraisal report", "valuer report"],
    "leaseAgreement": ["lease agreement", "lease deed", "rent agreement", "tenant agreement"],
    "taxReceipt": ["tax receipt", "property tax receipt", "municipal receipt"],
    "insurancePolicy": ["insurance policy", "policy document", "property insurance policy"],
    "approvalDocuments": ["approval documents", "noc documents", "approval files", "sanction documents"],
    "assignedUser": ["user", "assigned to", "owner user", "responsible person"],
    "taskStatus": ["action", "task", "workflow status", "activity"],
    "nextReviewDate": ["review date", "next action date", "follow up date"],
    "approvalStatus": ["approval", "approval state", "signoff status"],
    "remarks": ["comments", "notes", "remarks", "observation"],
    "alerts": ["alert", "warning", "notification", "flag"],
    "auditTrail": ["audit", "audit trail", "activity log", "change log"],
    "acquisitionDate": ["purchase date", "acquisition date", "deal date", "closing date"],
    "holdSellRedevelopDecision": ["strategy", "exit strategy", "hold sell", "redevelopment decision"],
    "targetExitValue": ["exit value", "target sale value", "target disposal value", "expected exit value"],
    "expectedSaleDate": ["sale date", "expected sale date", "exit date", "disposal date"],
    "exitIrr": ["exit irr", "target irr", "disposal irr"],
    "buyerInterest": ["buyer interest", "investor interest", "bidder interest"],
    "repairsStatus": ["repair status", "maintenance status", "r&m status"],
    "amcStatus": ["amc", "amc status", "maintenance contract", "annual maintenance contract"],
    "inspectionStatus": ["inspection", "inspection status", "audit status", "site inspection"],
    "complaintsOpen": ["open complaints", "complaints", "tenant complaints", "tickets open"],
    "utilitiesStatus": ["utility status", "electricity status", "water status", "power status"],
    "vendorName": ["vendor", "service provider", "facility vendor", "contractor"],
}


def field_examples(field: dict) -> list[str]:
    examples = FIELD_EXAMPLES.get(field["key"])
    if examples:
        return examples
    data_type = field.get("data_type")
    if data_type == "date":
        return ["2025-03-31", "31/03/2025", "Mar 31 2025"]
    if data_type in {"currency", "number", "integer"}:
        return ["1250000", "875000", "1800000"]
    if data_type == "percentage":
        return ["8.75", "8.75%", "0.0875"]
    if data_type == "file":
        return ["document.pdf", "file URL", "document link"]
    return [field["label"], "text value", "status/name/code"]


def field_aliases(field: dict) -> list[str]:
    aliases = [*field.get("aliases", []), *FIELD_DOMAIN_ALIASES.get(field["key"], [])]
    deduped = []
    seen = set()
    for alias in aliases:
        normalized = str(alias).strip().lower()
        if not normalized or normalized in seen:
            continue
        seen.add(normalized)
        deduped.append(alias)
    return deduped


def build_section_payload(section: dict) -> dict:
    return {
        "section_key": section["section_key"],
        "label": section["label"],
        "id_field": section["id_field"],
        "fields": [
            {
                "key": field["key"],
                "label": field["label"],
                "category": field.get("category"),
                "data_type": field.get("data_type"),
                "required": field.get("required", False),
                "alias_examples": field_aliases(field),
                "mapping_policy": "map_only_if_exact_value_exists" if field.get("category") == "derived" else "preferred_identifier" if field["key"] == section["id_field"] else "normal",
                "accepted_value_examples": field_examples(field),
            }
            for field in section["fields"]
        ],
    }
